import 'package:get/get.dart';
import 'package:my_flutter/data/model/response/language_model.dart';
import 'package:my_flutter/data/model/response/on_boarding_model.dart';

import 'images.dart';

class AppConstants {
  static const String APP_NAME = 'TestCash';
  //demo
  static const String BASE_URL = 'https://6cash-admin.6amtech.com';
  //
  // static const String BASE_URL = 'https://6cash-admin.6am.one';
  // //fun
  // static const String BASE_URL = 'https://6cash-admin.6am.fun';
  static const bool DEMO = true;
   static const double APP_VERSION = 2.1;

  static const String CUSTOMER_PHONE_CHECK_URI = '/api/v1/customer/auth/check-phone';
  static const String CUSTOMER_PHONE_RESEND_OTP_URI = '/api/v1/customer/auth/resend-otp';
  static const String CUSTOMER_PHONE_VERIFY_URI = '/api/v1/customer/auth/verify-phone';
  static const String CUSTOMER_REGISTRATION_URI = '/api/v1/customer/auth/register';
  static const String CUSTOMER_UPDATE_PROFILE = '/api/v1/customer/update-profile';
  static const String CUSTOMER_LOGIN_URI = '/api/v1/customer/auth/login';
  static const String CUSTOMER_LOGOUT_URI = '/api/v1/customer/logout';
  static const String CUSTOMER_FORGET_PASS_OTP_URI = '/api/v1/customer/auth/forgot-password';
  static const String CUSTOMER_FORGET_PASS_VERIFICATION = '/api/v1/customer/auth/verify-token';
  static const String CUSTOMER_FORGET_PASS_RESET = '/api/v1/customer/auth/reset-password';
  static const String CUSTOMER_LINKED_WEBSITE= '/api/v1/customer/linked-website';
  static const String CUSTOMER_BANNER= '/api/v1/customer/get-banner';
  static const String CUSTOMER_TRANSACTION_HISTORY= '/api/v1/customer/transaction-history';
  static const String CUSTOMER_PURPOSE_URL = '/api/v1/customer/get-purpose';
  static const String CONFIG_URI = '/api/v1/config';
  static const String IMAGE_CONFIG_URL_API_NEED = '/storage/app/public/purpose/';
  static const String CUSTOMER_PROFILE_INFO = '/api/v1/customer/get-customer';
  static const String CUSTOMER_CHECK_OTP = '/api/v1/customer/check-otp';
  static const String CUSTOMER_VERIFY_OTP = '/api/v1/customer/verify-otp';
  static const String CUSTOMER_CHANGE_PIN = '/api/v1/customer/change-pin';
  static const String CUSTOMER_UPDATE_TWO_FACTOR = '/api/v1/customer/update-two-factor';
  static const String CUSTOMER_SEND_MONEY = '/api/v1/customer/send-money';
  static const String CUSTOMER_REQUEST_MONEY = '/api/v1/customer/request-money';
  static const String CUSTOMER_CASH_OUT = '/api/v1/customer/cash-out';
  static const String CUSTOMER_PIN_VERIFY = '/api/v1/customer/verify-pin';
  static const String CUSTOMER_ADD_MONEY = '/api/v1/customer/add-money';
  static const String FAQ_URI = '/api/v1/faq';
  static const String NOTIFICATION_URI = '/api/v1/customer/get-notification';
  static const String TRANSACTION_HISTORY_URI = '/api/v1/customer/transaction-history';
  static const String REQUESTED_MONEY_URI = '/api/v1/customer/get-requested-money';
  static const String ACCEPTED_REQUESTED_MONEY_URI = '/api/v1/customer/request-money/approve';
  static const String DENIED_REQUESTED_MONEY_URI = '/api/v1/customer/request-money/deny';
  static const String TOKEN_URI = '/api/v1/customer/update-fcm-token';
  static const String CHECK_CUSTOMER_URI = '/api/v1/check-customer';
  static const String CHECK_AGENT_URI = '/api/v1/check-agent';
  static const String WON_REQUESTED_MONEY = '/api/v1/customer/get-own-requested-money';
  static const String CUSTOMER_REMOVE = '/api/v1/customer/remove-account';
  static const String UPDATE_KYC_INFORMATION = '/api/v1/customer/update-kyc-information';
  static const String WITHDRAW_METHOD_LIST = '/api/v1/customer/withdrawal-methods';
  static const String WITHDRAW_REQUEST = '/api/v1/customer/withdraw';
  static const String GET_WITHDRAWAL_REQUEST = '/api/v1/customer/withdrawal-requests';


  // Shared Key
  static const String THEME = 'theme';
  static const String TOKEN = 'token';
  static const String CUSTOMER_COUNTRY_CODE = 'customer_country_code';//not in project
  static const String LANGUAGE_CODE = 'language_code';
  static const String CART_LIST = 'cart_list';
  static const String USER_PASSWORD = 'user_password';
  static const String USER_ADDRESS = 'user_address';
  static const String USER_NUMBER = 'user_number';
  static const String SEARCH_ADDRESS = 'search_address';
  static const String TOPIC = 'notify';
  static const String CONFIG = 'config';
  static const String CUSTOMER_NAME = 'customer_name';
  static const String COUNTRY_CODE = 'country_code';
  static const String CUSTOMER_NUMBER = 'customer_number';
  static const String CUSTOMER_QR_CODE = 'customer_qr_code';
  static const String SEND_MONEY_SUGGEST_LIST = 'send_money_suggest';
  static const String REQUEST_MONEY_SUGGEST_LIST = 'request_money_suggest';
  static const String RECENT_AGENT_LIST = 'recent_agent_list';

  static const String PENDING = 'pending';
  static const String APPROVED = 'approved';
  static const String DENIED = 'denied';
  static const String CASH_IN = 'cash_in';
  static const String CASH_OUT = 'cash_out';
  static const String SEND_MONEY = 'send_money';
  static const String RECEIVED_MONEY = 'received_money';
  static const String ADMIN_CHARGE = 'admin_charge';
  static const String ADD_MONEY = 'add_money';
  static const String WITHDRAW = 'withdraw';
  static const String PAYMENT = 'payment';

  static const String BIOMETRIC_AUTH = 'biometric_auth';
  static const String BIOMETRIC_PIN = 'biometric';
  static const String CONTACT_PERMISSION = '';


  //topic
  static const String ALL = 'all';
  static const String USERS = 'customers';

  // App Theme
  static const String THEME_1 = 'theme_1';
  static const String THEME_2 = 'theme_2';
  static const String THEME_3 = 'theme_3';

  //input balance digit length
  static const int BALANCE_INPUT_LEN = 10;

  static List<LanguageModel> languages = [
    LanguageModel(imageUrl: Images.english, languageName: 'English', countryCode: 'US', languageCode: 'en'),
    LanguageModel(imageUrl: Images.saudi, languageName: 'Arabic', countryCode: 'SA', languageCode: 'ar'),

  ];

  static  List<OnboardModel> onboardList = [
    OnboardModel(Images.onboard_image_1, Images.onboard_background_1, 'on_boarding_title_1'.tr, 'on_boarding_sub_title_1'.tr),
    OnboardModel(Images.onboard_image_2, Images.onboard_background_2, 'on_boarding_title_2'.tr, 'on_boarding_sub_title_2'.tr),
    OnboardModel(Images.onboard_image_3, Images.onboard_background_3, 'on_boarding_title_3'.tr, 'on_boarding_sub_title_3'.tr),
  ];
  static var ar = {
  "home": "مسكن",
  "on_boarding_title_1" : "إرسال الأموال !",
  "on_boarding_sub_title_1" : "أرسل الأموال من 6Cash بسهولة في أي وقت ومن أي مكان",
  "on_boarding_title_2" : "المصروفات !",
  "on_boarding_sub_title_2" : "أصبح سحب الأموال أسهل ، فما عليك سوى إدخال رقم الحساب والمبلغ وسحب الأموال",
  "on_boarding_title_3" : "طلب المال !",
  "on_boarding_sub_title_3" : "طلب الأموال باستخدام حساب 6Cash لأي صديق في أي وقت في جميع أنحاء البلاد بسهولة",
  "create_account_description": "قم بإنشاء حساب 6Cash باستخدام رقم هاتفك المحمول للاستفادة من جميع المزايا",
  "welcome_to": "مرحبا بكم في 6 كاش!",
  "enter_name_or_number": "إدخال اسم أو رقم",
  "please_input_your_valid_number": "الرجاء إدخال رقمك الصحيح",
  "history":"تاريخ",
  "notification":"إشعار",
  "profile":"الملف الشخصي",
  "your_balance":"رصيدك",
  "add_money":"إضافة المال",
  "send_money":"إرسال الأموال",
  "cash_out":"المصروفات",
  "request_money":"طلب المال",
  "refer_friend":"ادع صديق",
  "linked_website":"المواقع المرتبطة",
  "all_transaction":"كل المعاملات",
  "others":"آخرون",
  "dark_mode":"الوضع الداكن",
  "make_payment":"قم بالدفع",
  "available_balance":"الرصيد المتوفر",
  "language": "الإنجليزية",
  "scan_qr_code": "مسح رمز الاستجابة السريعة ",
  "suggested": "مقترح",
  "phone_book": "دليل التلفونات",
  "for_person": "لشخص",
  "amount_in_bdt": "كمية",
  "4digit_pin": "4 أرقام PIN ",
  "new_balance": "الرصيد الجديد",
  "confirm_to_send_money": "تأكيد لإرسال الأموال ",
  "do_you_want_to_exit_the_app": "هل تريد الخروج من التطبيق",
  "this_feature_will_added_soon": "ستتم إضافة هذه الميزة قريبًا!",
  "back_to_home": "العودة إلى المنزل",
  "exit": "خروج",
  "swipe_to_confirm": "اسحب للتأكيد",
  "confirm_to_request_money": "تأكيد لطلب المال",
  "send_money_successful": "تم إرسال الأموال بنجاح",
  "request_send_successful": "تم إرسال الطلب بنجاح!",
  "agent_name_or_number": "اسم أو رقم الوكيل",
  "recent_agent": "وكيل حديث",
  "for_agent": "عن وكيل",
  "confirm_to_cash_out": "تأكيد على السحب النقدي",
  "cash_out_successful": "سحب الأموال بنجاح",
  "receiver": "إضافة المال",
  "setting": "إطار",
  "change_pin": "تغيير PIN",
  "change_language": "تغيير اللغة",
  "6cash_support": "سند",
  "24_support": "24/7 دعم",
  "faq": "التعليمات",
  "policies": "سياسات",
  "terms": "شروط الاستخدام",
  "account": "حساب",
  "logout": "تسجيل خروج",
  "download": "تحميل",
  "save": "يحفظ",
  "allow": "سمح",
  "no_connection": "لا يوجد اتصال متاح",
  "connected": "الاتصال متاح",
  "go_to_settings": "اذهب للاعدادات",
  "audio_permission": "إذن الصوت",
  "camera_permission": "إذن الكاميرا",
  "you_must_allow_permission_for_further_use": "يجب أن تسمح بإذن لمزيد من الاستخدام",
  "privacy_policy": "سياسة الخصوصية",
  "take_a_selfie": "خذ صورة شخصية",
  "email_address": "عنوان البريد الالكترونى",
  "optional": "اختياري",
  "type_email_address": "اكتب عنوان البريد الإلكتروني",
  "proceed": "تصرف",
  "male": "ذكر",
  "female": "أنثى",
  "other": "آخر",
  "first_name_or_last_name": "يجب ألا يكون الاسم الأول أو اسم العائلة فارغًا",
  "set_your_4_digit": "قم بتعيين رقم التعريف الشخصي المكون من 4 أرقام لتسجيل الدخول في المستقبل",
  "set_your_pin": "قم بتعيين رقم التعريف الشخصي الخاص بك",
  "confirm_pin": "تأكيد PIN",
  "place_your_face_inside_the_frame": "ضع وجهك داخل الإطار واضغط على الزر لالتقاط الصورة.",
  "4_digit_pin": "4 أرقام PIN",
  "hi": "مرحبا!",
  "amount": "كمية",
  "note": "مذكرة",
  "hi_user": "مرحبا المستخدم",
  "select_language": "اختار اللغة",
  "you_can_change_language": "يمكنك تغيير اللغة",
  "no_note_available": "لا توجد ملاحظة متاحة",
  "good_morning": "صباح جميل",
  "good_afternoon": "طاب مسائك",
  "good_evening": "مساء الخير",
  "good_night": "طاب مساؤك",
  "no_contact_available": "لا يوجد اتصال متاح",
  "welcome_back": "مرحبًا بعودتك",
  "forget_password": "هل نسيت رقم التعريف الشخصي؟",
  "forget_password_appbar": "نسيت رقم التعريف الشخصي",
  "forget_pass_long_text": "يرجى تقديم رقم هاتفك لتغيير رقم التعريف الشخصي الخاص بك",
  "Send_for_otp": "أرسل إلى OTP",
  "login": "تسجيل الدخول",
  "login_registration": "تسجيل الدخول / التسجيل",
  "information": "معلومة",
  "title": "عنوان",
  "resend": " إعادة إرسال",
  "resend_otp_in": "إعادة إرسال OTP بتنسيق",
  "seconds": "ثواني",
  "phone_number_verification": "التحقق من رقم الهاتف",
  "verification_long_text": "لقد أرسلنا رمز التحقق إلى رقم هاتفك المحمول",
  "Change_Number": "تغيير رقم",
  "choice_screen_title": "تسجيل رقم الهاتف المحمول و NID دقيقة واحدة",
  "choice_screen_subtitle": "تعلم تقريبًا أي مهارة وأنت مرتاح في منزلك من خلال تطبيقنا.",
  "Set_new_4_digit_pin": "قم بتعيين دبوس جديد مكون من 4 أرقام",
  "Confirm_Password": "تأكيد PIN",
  "are_you_sure": "هل أنت واثق؟",
  "do_you_want_to_exit_add_money": "هل تريد الخروج من إضافة أموال؟",
  "no": "رقم",
  "yes": "نعم",
  "are_you_sure_you_want_to_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "something_error_in_your_phone_number": "شيء خطأ في رقم هاتفك",
  "two_factor_authentication": "توثيق ذو عاملين",
  "two_factor_authentication_status": "اثنان عامل حالة المصادقة",
  "old_password": "رقم التعريف الشخصي القديم",
  "new_password": "دبوس جديد",
  "confirm_password": "تأكيد PIN",
  "we_have_send_the_code": "لقد أرسلنا رمز التحقق إلى رقم هاتفك المحمول",
  "change_number": "تغيير رقم",
  "please_give_your_phone_number": "يرجى إعطاء رقم هاتفك",
  "phone_number_not_contain_characters": "رقم الهاتف لا يحتوي على أحرف",
  "phone_number_not_contain_spatial_characters": "رقم الهاتف لا يحتوي على طابع مكاني",
  "pin_not_matched": "رقم التعريف الشخصي غير متطابق",
  "phone_verification": "التحقق من الهاتف",
  "successfully_login": "تم تسجيل الدخول بنجاح",
  "please_enter_your_account": "الرجاء إدخال حسابك",
  "create_account":"إصنع حساب",
  "please_enter_your_valid_pin":"الرجاء إدخال رقم التعريف الشخصي الخاص بك صالح",
  "enter_your_pin":"أدخل الكود الشخصي التعريفي",
  "pin_should_be_4_digit":"يجب أن يتكون الدبوس من 4 أرقام",
  "start_exploring_the_amazing_ways_to_take_your_lifestyle_upward":"ابدأ في استكشاف الطرق المذهلة للارتقاء بنمط حياتك ...",
  "edit_profile":"تعديل الملف الشخصي",
  "alert":"انذار",
  "your_information_will_remove":"ستتم إزالة معلوماتك",
  "please_provide_valid_email":"يرجى تقديم بريد إلكتروني صالح",
  "pin_change":"تغيير الدبوس",
  "my_qr_code":"رمز الاستجابة السريعة الخاص بي",
  "first_name":"الاسم الاول",
  "last_name":"اللقب",
  "email":"بريدك الالكتروني",
  "occupation":"إشغال",
  "select_your_gender":"اختر جنسك",
  "gender":"جنس",
  "select_occupation":"حدد المهنة",
  "otp_verification" : "التحقق من OTP",
  "on" : "عن",
  "off" : "إيقاف",
  "cash_in" : "التدفقات النقدية الداخلة",
  "request_number" : "رقم الطلب",
  "please_login_again" : "الرجاد الدخول على الحساب من جديد",
  "please_input_4_digit_pin" : "يرجى إدخال رقم التعريف الشخصي المكون من 4 أرقام",
  "input_field_is_empty" : "حقل الإدخال فارغ",
  "you_have_to_grand_permission_to_see_contact" : "يجب عليك منح الإذن لرؤية جهة الاتصال",
  "please_allow_permission" : "يرجى السماح بإذن للاتصال",
  "verify_umber" : "تحقق من الرقم",
  "payment_done": "تم الدفع",
  "your_payment_successfully_done": "تم الدفع الخاص بك بنجاح",
  "payment_failed": "عملية الدفع فشلت",
  "your_payment_failed": "فشل الدفع الخاص بك",
  "payment_cancelled": "تم إلغاء الدفع",
  "your_payment_cancelled": "تم إلغاء الدفع الخاص بك",
  "no_data_found": "لاتوجد بيانات",
  "share_statement" : "بيان المشاركة",
  "no_notification_found": "لم يتم العثور على إعلام",
  "accept": "قبل",
  "clear_logout": "مسح & تسجيل الخروج",
  "deny": "رفض",
  "no_provided": "لم تقدم",
  "view_all": "مشاهدة الكل",
  "requested_money": "طلب المال",
  "requested_money_list": "قائمة الأموال المطلوبة",
  "pending": "ريثما",
  "accepted": "وافقت",
  "denied": "رفض",
  "need_any_help" : "هل تحتاج الى مساعدة",
  "feel_free_to_contact" : "لا تتردد في الاتصال بنا في أي وقت. \n نحن ندعم 247 ساعة",
  "make_call" : "قم بإجراء مكالمة",
  "send_email" : "ارسل بريد الكتروني",
  "all": "الجميع",
  "user": "المستعمل",
  "qr_code_save_to_your_gallery": "حفظ رمز الاستجابة السريعة في معرض الصور الخاص بك",
  "share_QR_code": "مشاركة رمز الاستجابة السريعة",
  "scan_the_QR_code_to_send_money": "امسح رمز الاستجابة السريعة ضوئيًا لإرسال الأموال",
  "are_you_sure_want_to_accept": "هل أنت متأكد أنك تريد إرسال الأموال إلى هذا الرقم؟",
  "are_you_sure_want_to_denied": "هل أنت متأكد أنك تريد رفض الطلب من هذا الرقم؟",
  "request_accepted_successfully": "تم قبول الطلب بنجاح",
  "request_denied_successfully": "تم رفض الطلب بنجاح",
  "requests": "الطلبات",
  "no_recent_agent_available" : "لا يوجد وكيل حديث متاح",
  "save_future_cash_out" : "ادخر لصرف النقود في المستقبل",
  "to" : " إلى ",
  "charge" : "تهمة",
  "insufficient_balance" : "رصيد غير كاف",
  "change_purpose" : "غرض التغيير",
  "please_input_valid_phone_number" : "الرجاء إدخال رقم هاتف صحيح",
  "please_input_amount": "الرجاء إدخال المبلغ",
  "select_your_purpose" : "حدد الغرض الخاص بك",
  "received_money": "النقود المستلمة",
  "successful": "ناجح",
  "web_view": "عرض الويب",
  "about_us": "معلومات عنا",
  "select_a_transaction": "حدد معاملة",
  "to_money_login_attempts": "محاولات تسجيل دخول كثيرة جدًا. محظور لمدة 1 دقيقة",
  "send_requests": "ارسل طلبات",
  "trx_id": "معرف Trx",
  "transaction_amount_must_be": "يجب أن يكون مبلغ المعاملة أكبر من الصفر",
  "confirm_to": "تأكيد ل",
  "Please_enter_a_different_customer_number": "الرجاء إدخال رقم عميل مختلف للمعاملة بخلاف رقمك الخاص",
  "for_demo_1234": "للعرض التوضيحي OTP هو 1234",
  "please_authenticate_to_easy_access_for_next_time": "يرجى المصادقة للوصول السهل في المرة القادمة",
  "please_authenticate_to_login": "يرجى المصادقة لتسجيل الدخول",
  "biometric_login": "تسجيل الدخول البيومتري",
  "your_account_remove_successfully": "تمت إزالة حسابك بنجاح",
  "there_is_a_problem_on_removing_your_account": "هناك مشكلة في إزالة حسابك",
  "delete_account": "حذف الحساب",
  "are_you_sure_to_delete_account": "هل أنت متأكد من حذف حسابك؟",
  "it_will_remove_your_all_information": "سوف يزيل كل المعلومات الخاصة بك.",
  "no_user": "لا يوجد مستخدم",
  "kyc_verification": "تَحَقّق",
  "kyc_verification_is_not": "التحقق لم يكتمل.",
  "click_to_verify": "انقر للتحقق",
  "identity_number": "تحديد الرقم",
  "upload_your_image": "قم بتحميل صورتك",
  "upload": "تحميل",
  "identity_number_is_empty": "رقم التعريف فارغ",
  "please_upload_identity_image": "الرجاء تحميل صورة الهوية",
  "select_identity_type": "حدد نوع الهوية",
  "passport": "جواز سفر",
  "driving_licence": "رخصة قيادة",
  "trade_license": "رخصة تجارية",
  "nid": "ليس",
  "straighten_your_face": "افرد وجهك أمام الكاميرا وارمش عينيك",
  "straighten_smile": "افرد وجهك أمام الكاميرا وابتسم",
  "processing_image": "معالجة الصورة",
  "face_verification": "التحقق من الوجه",
  "sorry_your_face_could_not_detect": "آسف ! وجهك لا يمكن أن يكتشف بنجاح",
  "retry": "حاكم من جديد",
  "cancel": "إلغاء",
  "face_scanning_successful": "اكتمل مسح الوجه بنجاح!",
  "please_verify_your_kyc_information": "يرجى التحقق من المعلومات الخاصة بك.",
  "scanner": "إخصائي الأشعة فوق الصوتية",
  "user_unavailable": "المستخدم غير متوفر",
  "skip": "تخطى",
  "please_disable_the_vpn": "يرجى تعطيل vpn لاستخدام هذا التطبيق",
  "your_verification_request_is": "طلب التحقق الخاص بك معلق ، يرجى انتظار الموافقة",
  "withdraw": "سحب",
  "withdraw_request": "طلب سحب",
  "enter_agent_number": "أدخل اسم الوكيل",
  "withdraw_method": "طريقة السحب",
  "selected_a_method": "حدد طريقة",
  "your_verification_is_denied": "تم رفض التحقق الخاص بك ، يرجى تقديم مرة أخرى",
  "re_apply": "أعد التقديم",
  "edit": "يحرر",
  "please_provide_valid_date": "يرجى تقديم تاريخ صالح",
  "must_use_country_code": "يجب استخدام رمز البلد",
  "by_proceeding_you": "بالمتابعة فإنك توافق على",
  "if_you_allow_contact_permission": "إذا سمحت بإذن الاتصال ، يمكنك التعامل بسهولة",
  "contact_permission": "إذن الاتصال",
  "payment": "قسط",
  "request_status": "حالة الطلب",
  "withdraw_history": "سحب التاريخ",
  "pending_balance": "رصيد معلق",
  "sent": "أرسلت",
  "withdraw_req": "سحب الطلب."

  };
  static var en = {
    "home": "Home",
    "on_boarding_title_1" : "Send Money !",
    "on_boarding_sub_title_1" : "Send money from 6Cash easily at anytime from anywhere",
    "on_boarding_title_2" : "Cash Out !",
    "on_boarding_sub_title_2" : "Withdraw money is even more easier.Just enter account number and amount and withdraw money",
    "on_boarding_title_3" : "Request Money !",
    "on_boarding_sub_title_3" : "Request for Money using 6Cash account to any friend anytime around the country easily",
    "create_account_description": "Create 6Cash account with your mobile number to get all the benefits",
    "welcome_to": "Welcome to 6Cash !",
    "enter_name_or_number": "Enter Name or Number",
    "please_input_your_valid_number": "Please input your valid number",
    "history":"History",
    "notification":"Notification",
    "profile":"Profile",
    "your_balance":"Your Balance",
    "add_money":"Add Money",
    "send_money":"Send Money",
    "cash_out":"Cash Out",
    "request_money":"Request Money",
    "refer_friend":"Refer Friend",
    "linked_website":"Linked Websites ",
    "all_transaction":"All Transaction",
    "others":"Others",
    "dark_mode":"Dark Mode",
    "make_payment":"Make Payment",
    "available_balance":"Available Balance",
    "language": "English",
    "scan_qr_code": "Scan QR Code",
    "suggested": "Suggested",
    "phone_book": "Phone Book",
    "for_person": "For Person",
    "amount_in_bdt": "Amount",
    "4digit_pin": "4 Digit PIN",
    "new_balance": "New Balance",
    "confirm_to_send_money": "Confirm to Send Money",
    "do_you_want_to_exit_the_app": "Do you want to exit the App",
    "this_feature_will_added_soon": "This feature will added soon !",
    "back_to_home": "Back to Home",
    "exit": "Exit",
    "swipe_to_confirm": "Swipe to Confirm",
    "confirm_to_request_money": "Confirm to Request Money",
    "send_money_successful": "Send Money Successful",
    "request_send_successful": "Request Send Successful!",
    "agent_name_or_number": "Agent Name or Number",
    "recent_agent": "Recent Agent",
    "for_agent": "For Agent",
    "confirm_to_cash_out": "Confirm to Cash Out",
    "cash_out_successful": "Cash Out Successful",
    "receiver": "Add Money",
    "setting": "SETTINGS",
    "change_pin": "Change PIN",
    "change_language": "Change Language",
    "6cash_support": "Support",
    "24_support": "24/7 Support",
    "faq": "FAQ",
    "policies": "POLICIES",
    "terms": "Terms of Use",
    "account": "Account",
    "logout": "LogOut",
    "download": "Download",
    "save": "Save",
    "allow": "Allow",
    "no_connection": "No Connection Available",
    "connected": "Connection Available",
    "go_to_settings": "Go to Settings",
    "audio_permission": "Audio Permission",
    "camera_permission": "Camera Permission",
    "you_must_allow_permission_for_further_use": "You must allow permission for further use",
    "privacy_policy": "Privacy Policy",
    "take_a_selfie": "Take a selfie",
    "email_address": "Email Address",
    "optional": "Optional",
    "type_email_address": "Type Email Address",
    "proceed": "Proceed",
    "male": "Male",
    "female": "Female",
    "other": "Other",
    "first_name_or_last_name": "First name Or last name must not be Empty",
    "set_your_4_digit": "Set Your 4 Digit PIN For Future Login",
    "set_your_pin": "Set Your PIN",
    "confirm_pin": "Confirm PIN",
    "place_your_face_inside_the_frame": "Place your face inside the frame and press the button to capture image.",
    "4_digit_pin": "4 Digit PIN",
    "hi": "Hi",
    "amount": "Amount",
    "note": "Note",
    "hi_user": "Hi user",
    "select_language": "Select Language",
    "you_can_change_language": "You can change language",
    "no_note_available": "No note available",
    "good_morning": "Good Morning",
    "good_afternoon": "Good Afternoon",
    "good_evening": "Good Evening",
    "good_night": "Good Night",
    "no_contact_available": "No Contact Available",
    "welcome_back": "Welcome back",
    "forget_password": "Forget PIN?",
    "forget_password_appbar": "Forget PIN",
    "forget_pass_long_text": "Please provide your phone number for changing your PIN",
    "Send_for_otp": "Send for OTP",
    "login": "Login",
    "login_registration": "Login / Registration",
    "information": "Information",
    "title": "Title",
    "resend": "Resend ",
    "resend_otp_in": "Resend OTP in ",
    "seconds": "seconds",
    "phone_number_verification": "Phone Number Verification",
    "verification_long_text": "We have send the code verification to Your Mobile Number",
    "Change_Number": "Change Number",
    "choice_screen_title": "Mobile Number & NID Register One minutes",
    "choice_screen_subtitle": "Learn almost any skill from a comfort of your home with our app.",
    "Set_new_4_digit_pin": "Set new 4 digit pin",
    "Confirm_Password": "Confirm PIN",
    "are_you_sure": "Are you sure?",
    "do_you_want_to_exit_add_money": "Do you want to exit Add Money?",
    "no": "No",
    "yes": "Yes",
    "are_you_sure_you_want_to_logout": "Are you sure,You want to logout?",
    "something_error_in_your_phone_number": "Something error in your phone number",
    "two_factor_authentication": "Two Factor Authentication",
    "two_factor_authentication_status": "Two Factor Authentication Status",
    "old_password": "Old PIN",
    "new_password": "New PIN",
    "confirm_password": "Confirm PIN",
    "we_have_send_the_code": "We have send the code verification to Your Mobile Number",
    "change_number": "Change Number",
    "please_give_your_phone_number": "Please give your phone number",
    "phone_number_not_contain_characters": "Phone number not contain Characters",
    "phone_number_not_contain_spatial_characters": "Phone number not contain spatial character",
    "pin_not_matched": "Pin not matched",
    "phone_verification": "Phone Verification",
    "successfully_login": "Successfully login",
    "please_enter_your_account": "Please enter your Account",
    "create_account":"Create Account",
    "please_enter_your_valid_pin":"Please enter your valid pin",
    "enter_your_pin":"Enter your pin",
    "pin_should_be_4_digit":"Pin should be 4 digit",
    "start_exploring_the_amazing_ways_to_take_your_lifestyle_upward":"Start exploring the amazing ways to take your lifestyle upward...",
    "edit_profile":"Edit Profile",
    "alert":"Alert",
    "your_information_will_remove":"Your information will remove",
    "please_provide_valid_email":"Please provide valid email",
    "pin_change":"Pin Change",
    "my_qr_code":"My QR Code",
    "first_name":"First name",
    "last_name":"Last name",
    "email":"Your Email",
    "occupation":"Occupation",
    "select_your_gender":"Select Your Gender",
    "gender":"Gender",
    "select_occupation":"Select Occupation",
    "otp_verification" : "OTP Verification",
    "on" : "ON",
    "off" : "OFF",
    "cash_in" : "Cash In",
    "request_number" : "Request Number",
    "please_login_again" : "Please login again",
    "please_input_4_digit_pin" : "Please Input 4 Digit Pin",
    "input_field_is_empty" : "Input field is empty",
    "you_have_to_grand_permission_to_see_contact" : "You have to grant permission to see contact",
    "please_allow_permission" : "Please Allow Permission for Contact ",
    "verify_umber" : "Verify Number",
    "payment_done": "Payment done",
    "your_payment_successfully_done": "Your payment successfully done",
    "payment_failed": "Payment failed",
    "your_payment_failed": "Your payment failed",
    "payment_cancelled": "Payment Cancelled",
    "your_payment_cancelled": "Your payment cancelled",
    "no_data_found": "No data found",
    "share_statement" : "Share Statement",
    "no_notification_found": "No Notification Found",
    "accept": "Accept",
    "clear_logout": "Clear & Logout",
    "deny": "Deny",
    "no_provided": "No provided",
    "view_all": "View All",
    "requested_money": "Request for money",
    "requested_money_list": "Requested money list",
    "pending": "Pending",
    "accepted": "Accepted",
    "denied": "Denied",
    "need_any_help" : "Need Any Help",
    "feel_free_to_contact" : "Feel free to contact us any time.\nWe support 24/7 Hour",
    "make_call" : "Make Call",
    "send_email" : "Send Email",
    "all": "All",
    "user": "User",
    "qr_code_save_to_your_gallery": "QR code save to your Gallery",
    "share_QR_code": "Share QR Code",
    "scan_the_QR_code_to_send_money": "Scan the QR code to send Money",
    "are_you_sure_want_to_accept": "Are you sure you want to send money to this number?",
    "are_you_sure_want_to_denied": "Are you sure you want to deny request from this number?",
    "request_accepted_successfully": "Request accepted successfully",
    "request_denied_successfully": "Request denied successfully",
    "requests": "Requests",
    "no_recent_agent_available" : "No recent Agent Available",
    "save_future_cash_out" : "Save for future Cash Out",
    "to" : " to ",
    "charge" : "Charge",
    "insufficient_balance" : "Insufficient Balance",
    "change_purpose" : "Change Purpose",
    "please_input_valid_phone_number" : "Please input valid Phone Number",
    "please_input_amount": "Please input amount",
    "select_your_purpose" : "Select your purpose",
    "received_money": "Received Money",
    "successful": "Successful",
    "web_view": "Web View",
    "about_us": "About us",
    "select_a_transaction": "Select a transaction",
    "to_money_login_attempts": "Too many login attempts. Banned for 1 minute",
    "send_requests": "Send Requests",
    "trx_id": "TrxID",
    "transaction_amount_must_be": "Transaction  amount must be greater than zero",
    "confirm_to": "Confirm to",
    "Please_enter_a_different_customer_number": "Please enter a different customer number to Transaction to other than your own number",
    "for_demo_1234": "For demo OTP is 1234",
    "please_authenticate_to_easy_access_for_next_time": "Please authenticate to easy access for next time",
    "please_authenticate_to_login": "Please authenticate to login",
    "biometric_login": "Biometric Login",
    "your_account_remove_successfully": "Your account remove successfully",
    "there_is_a_problem_on_removing_your_account": "There is a problem on removing your account",
    "delete_account": "Delete Account",
    "are_you_sure_to_delete_account": "Are you sure to delete your account?",
    "it_will_remove_your_all_information": "It will remove your all information.",
    "no_user": "No user",
    "kyc_verification": "Verification",
    "kyc_verification_is_not": "Verification is not complete. ",
    "click_to_verify": "Click to verify",
    "identity_number": "Identify Number",
    "upload_your_image": "Upload your image",
    "upload": "Upload",
    "identity_number_is_empty": "Identification number is empty",
    "please_upload_identity_image": "Please upload identity image",
    "select_identity_type": "Select Identity Type",
    "passport": "Passport",
    "driving_licence": "Driving licence",
    "trade_license": "Trade Licence",
    "nid": "NID",
    "straighten_your_face": "Straighten your face in front of camera and blink your Eyes",
    "straighten_smile": "Straighten your face in front of camera and smile",
    "processing_image": "Processing image",
    "face_verification": "Face Verification",
    "sorry_your_face_could_not_detect": "Sorry ! Your face could not detect successfully",
    "retry": "Retry",
    "cancel": "Cancel",
    "face_scanning_successful": "Face scanning successfully completed !",
    "please_verify_your_kyc_information": "Please verify your information.",
    "scanner": "Scanner",
    "user_unavailable": "User Unavailable",
    "skip": "Skip",
    "please_disable_the_vpn": "Please disable the vpn to use this app",
    "your_verification_request_is": "Your Verification request is pending, please wait for approve",
    "withdraw": "Withdraw",
    "withdraw_request": "Withdraw Request",
    "enter_agent_number": "Enter agent name",
    "withdraw_method": "Withdraw Method",
    "select_a_method": "Select a method",
    "your_verification_is_denied": "Your verification request is denied, please submit again",
    "re_apply": "Re-apply",
    "edit": "Edit",
    "please_provide_valid_date": "Please provide valid date",
    "must_use_country_code": "Must use country code",
    "by_proceeding_you": "By proceeding you agree to our ",
    "if_you_allow_contact_permission": "If you Allow contact permission, you can transaction easily",
    "contact_permission": "Contact permission",
    "payment": "Payment",
    "request_status": "Request Status",
    "withdraw_history": "Withdraw History",
    "pending_balance": "Pending Balance",
    "sent": "Sent",
    "withdraw_req": "Withdraw Req."

  };
}
