name: my_flutter
description: A new Flutter project.
publish_to: 'none' #

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  intl: ^0.17.0
  google_fonts: ^3.0.1
  firebase_remote_config: ^2.0.17
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  connectivity_plus: ^3.0.2
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  dotted_border: ^2.0.0+1
  flutter_contacts: ^1.1.4
  azlistview: ^2.0.0
  pin_code_fields: ^7.3.0
  modal_bottom_sheet: ^2.0.0
  slide_to_confirm: ^1.1.0
  lottie: ^1.2.1
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.4+4
  country_code_picker: ^2.0.2
  camera: ^0.10.0+4
  http: ^0.13.4
  carousel_slider: ^4.0.0
  webview_flutter: ^3.0.0
  flutter_svg: ^1.0.0
  device_preview: ^1.0.0
  flutter_html: ^3.0.0-alpha.1
  shimmer: ^2.0.0-nullsafety.0
  permission_handler: ^10.0.0
  share_plus: ^6.1.0
  screenshot: ^1.2.3
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.3.0
  phone_number: ^1.0.0
  path_drawing: ^1.0.0
  flutter_custom_tabs: ^1.0.4
  local_auth: ^2.1.0
  google_mlkit_barcode_scanning: ^0.4.0
  google_mlkit_face_detection: ^0.4.0
  cached_network_image: ^3.2.2
  flutter_secure_storage: ^6.0.0
  app_settings: ^4.1.8
  percent_indicator: ^4.2.2
  flutter_smart_dialog: ^4.6.2+1
  device_info_plus: ^8.0.0
  unique_identifier: ^0.2.2
  url_launcher: ^6.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600
  module:
    androidX: true
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter